### ISSUE TITLE
Source points to a local folder called github.com

### ISSUE THREAD

**Issue by proligde** [bestform/souparchive#3]
Steps to reproduce:

- clone github repo to /opt/souparchive
- cd to /opt/souparchive
- make freebsd

Expected result:

souparchive builds

Actual result:
`
main.go:12:2: cannot find package "github.com/bestform/souparchive/db" in any of:
       /usr/local/go/src/github.com/bestform/souparchive/db (from $GOROOT)
       ($GOPATH not set)
main.go:13:2: cannot find package "github.com/bestform/souparchive/feed" in any of:
       /usr/local/go/src/github.com/bestform/souparchive/feed (from $GOROOT)
       ($GOPATH not set)
main.go:14:2: cannot find package "github.com/bestform/souparchive/fetch" in any of:
       /usr/local/go/src/github.com/bestform/souparchive/fetch (from $GOROOT)
       ($GOPATH not set)
main.go:15:2: cannot find package "github.com/bestform/souparchive/host" in any of:
       /usr/local/go/src/github.com/bestform/souparchive/host (from $GOROOT)
       ($GOPATH not set)
`

Creating a symlink there as a workaround made it build successfully as far as I could see

**Comment by bestform** [comment]
you cannot clone the project into an arbitrary folder. It's got to be github.com/bestform/souparchive inside your GOPATH. That's just how go works. The best you can do is to just go get it:
```go get github.com/bestform/souparchive```
this will put it in the correct folder.

**Comment by proligde** [comment]
*showing myself out...*
